-- Semantic mind-map: precomputed UMAP projections + HDBSCAN clusters
-- over speech_chunks.embedding. Powers the /semantic-map page (3D + 2D
-- toggle) by giving every chunk a stable spatial coordinate and a
-- 3-level cluster hierarchy.
--
-- Three tables:
--
-- 1. projection_runs — one row per fit/cluster/label cycle. Run-id
--    scoping lets a re-projection compute alongside the live one and
--    swap atomically by flipping is_current. The API filters every
--    query by the single is_current=true row, so promotion takes
--    effect on the next request.
--
-- 2. speech_clusters — per-run, per-level cluster nodes. parent_id
--    builds the L1→L2→L3 tree. label is the top-3 TF-IDF terms joined;
--    top_terms is the full ranked list as JSONB. top_chunk_ids is the
--    15 representative chunks for the drawer's preview list.
--
-- 3. speech_chunk_projections — one row per chunk per run, holding 3D
--    coords (x,y,z), 2D coords (x2,y2), and the cluster_id at each of
--    the three levels. Noise points have NULL cluster_id_lN and still
--    render but aren't drillable.
--
-- DEPENDS ON: 0017 (speech_chunks). The chunk_id FK and ON DELETE
-- CASCADE keep this table in sync if a chunk row is ever deleted.
--
-- WHAT THIS DOES NOT DO: add a parallel embedding column. The Qwen3
-- vector on speech_chunks.embedding is and stays canonical. The (x,y,z)
-- columns here are derived state, regenerated by re-running the
-- pipeline.

-- ─── projection_runs ──────────────────────────────────────────────

create table if not exists projection_runs (
    id            uuid primary key default gen_random_uuid(),
    status        text not null
                      check (status in ('running','succeeded','failed','superseded')),

    -- Exactly zero or one row may have is_current=true. Promotion is a
    -- transactional flip: clear the old, set the new. The partial
    -- unique index below enforces this.
    is_current    boolean not null default false,

    -- Algorithm parameters captured for reproducibility:
    -- {umap: {n_neighbors, min_dist, n_components}, hdbscan: {l1, l2, l3 min_cluster_size},
    --  sample_size, embedding_model_at_run_time}
    params        jsonb not null,

    -- Counts populated as stages complete; useful for /admin
    -- dashboards and pipeline observability.
    chunk_count   integer,
    cluster_count_l1 integer,
    cluster_count_l2 integer,
    cluster_count_l3 integer,

    started_at    timestamptz not null default now(),
    finished_at   timestamptz,
    notes         text
);

-- At most one is_current=true row. Promotion clears the previous
-- current in the same transaction as setting the new one.
create unique index if not exists idx_projection_runs_current
    on projection_runs((is_current))
    where is_current = true;

create index if not exists idx_projection_runs_status_time
    on projection_runs(status, started_at desc);

-- ─── speech_clusters ──────────────────────────────────────────────

create table if not exists speech_clusters (
    id            bigserial primary key,
    run_id        uuid not null references projection_runs(id) on delete cascade,

    -- 1 = coarsest (~30 clusters), 2 = mid (~200), 3 = finest (~1500).
    level         smallint not null check (level in (1,2,3)),

    -- L1 rows have parent_id = NULL. L2 rows point at an L1 cluster.
    -- L3 rows point at an L2 cluster. Hierarchy is built by majority
    -- vote: each finer cluster is parented to whichever coarser cluster
    -- contains the plurality of its members.
    parent_id     bigint references speech_clusters(id) on delete cascade,

    -- Top-3 TF-IDF terms joined with ", ". Always non-null; if a
    -- cluster's tf-idf returns nothing meaningful, the labeller falls
    -- back to "(unlabelled cluster N)".
    label         text not null,
    label_method  text not null default 'tfidf',

    -- Full ranked term list: [{"term": "carbon tax", "weight": 0.42}, ...]
    top_terms     jsonb not null,

    member_count  integer not null,

    -- 3D centroid in the projection space.
    centroid_x    real,
    centroid_y    real,
    centroid_z    real,

    -- 2D centroid (separate UMAP fit, not a flattening of 3D).
    centroid_x2   real,
    centroid_y2   real,

    -- 10–20 chunk_ids closest to the centroid. Drives the cluster
    -- drawer's preview list without a points fetch.
    top_chunk_ids uuid[] not null,

    created_at    timestamptz not null default now()
);

create index if not exists idx_speech_clusters_run_level
    on speech_clusters(run_id, level);
create index if not exists idx_speech_clusters_parent
    on speech_clusters(parent_id) where parent_id is not null;

-- ─── speech_chunk_projections ─────────────────────────────────────

create table if not exists speech_chunk_projections (
    chunk_id      uuid primary key references speech_chunks(id) on delete cascade,
    run_id        uuid not null references projection_runs(id) on delete cascade,

    -- 3D coordinates (UMAP n_components=3).
    x             real not null,
    y             real not null,
    z             real not null,

    -- 2D coordinates (separate UMAP fit, n_components=2).
    x2            real not null,
    y2            real not null,

    -- Cluster assignments at each level. NULL = HDBSCAN noise (-1).
    cluster_id_l1 bigint references speech_clusters(id) on delete set null,
    cluster_id_l2 bigint references speech_clusters(id) on delete set null,
    cluster_id_l3 bigint references speech_clusters(id) on delete set null,

    projected_at  timestamptz not null default now()
);

create index if not exists idx_chunk_proj_run
    on speech_chunk_projections(run_id);
create index if not exists idx_chunk_proj_l1
    on speech_chunk_projections(cluster_id_l1) where cluster_id_l1 is not null;
create index if not exists idx_chunk_proj_l2
    on speech_chunk_projections(cluster_id_l2) where cluster_id_l2 is not null;
create index if not exists idx_chunk_proj_l3
    on speech_chunk_projections(cluster_id_l3) where cluster_id_l3 is not null;
