-- Schema split: move user/payment tables into a `private` schema so the
-- public legislative dataset (politicians / speeches / bills / votes / etc.)
-- can be redistributed via `pg_dump --schema=public` without ever touching
-- PII. The cross-schema FK from private.report_jobs.politician_id to
-- public.politicians.id is preserved automatically — Postgres tracks FK
-- targets by OID.
--
-- The companion `ALTER ROLE sw SET search_path = public` is applied in a
-- follow-up step *after* the application code has been updated to qualify
-- every private table reference. Until then, leaving search_path at its
-- default keeps unqualified queries working through the cutover.
--
-- ALTER TABLE ... SET SCHEMA atomically moves indexes, constraints,
-- sequences, partial-unique indexes, and triggers along with the table.
-- This migration is reversible by re-running with `private` and `public`
-- swapped, but: do not edit this file once applied; write a new forward
-- migration if you need to walk it back.

CREATE SCHEMA IF NOT EXISTS private;

ALTER TABLE public.users                        SET SCHEMA private;
ALTER TABLE public.login_tokens                 SET SCHEMA private;
ALTER TABLE public.saved_searches               SET SCHEMA private;
ALTER TABLE public.correction_submissions       SET SCHEMA private;
ALTER TABLE public.credit_ledger                SET SCHEMA private;
ALTER TABLE public.credit_purchases             SET SCHEMA private;
ALTER TABLE public.stripe_webhook_events        SET SCHEMA private;
ALTER TABLE public.rate_limit_increase_requests SET SCHEMA private;
ALTER TABLE public.report_jobs                  SET SCHEMA private;
ALTER TABLE public.report_bug_reports           SET SCHEMA private;
