-- 0110 — Newmarket: retire the mirror generation, and gain Ward 5.
--
-- ★ WE WERE MISSING WARD 5 — a HOLE, not a trailing gap. Held rows were
-- Wards 1, 2, 3, 4, 6 and 7, so every address in Ward 5 resolved to no
-- councillor at all. The remaining six overlap the authoritative map at 99.6%
-- or better, so this is a coverage repair on an otherwise-correct set.
--
-- ⚠ It was found by auditing held district count against AMO's 2026 roster —
-- the same check that surfaced Windsor's ninth-of-ten and Burlington's
-- four-of-six. Fifth partial-ingest defect in this programme, and the second
-- that is an interior hole rather than a truncation (Markham is missing Ward 7
-- on the same pattern, still pending an in-force date).
--
-- ★ IN-FORCE DATE IS THE PUBLISHER'S OWN PROSE, not a layer title and not a
-- metadata date: "Since 2003 the Town of Newmarket has had a ward system of
-- representation on Town Council. This system contains seven wards."
-- ⚠ 2003-11-10 is a NOVEMBER election. Ontario's fixed fourth-Monday-of-October
-- rule begins only with 2010, so a date generated by that rule is wrong here.
--
-- ⚠ RESIDUAL UNCERTAINTY, RECORDED RATHER THAN HIDDEN. That sentence dates the
-- seven-ward SYSTEM, not necessarily these exact boundaries — a within-system
-- adjustment after 2003 would not contradict it. The count matches at seven and
-- no review is documented, but this is weaker than a by-law and should be
-- upgraded if one is found. It is still strictly better than the mirror's
-- 2023-01-01, which is false rather than merely imprecise.
--
-- Forward-only. Apply with:
--   docker exec -i sw-db psql -U sw -d sovereignwatch -v ON_ERROR_STOP=1 \
--     < db/migrations/0110_newmarket_ward5.sql

BEGIN;

DO $$
DECLARE auth int;
BEGIN
    SELECT count(*) INTO auth FROM constituency_boundaries
     WHERE source_set = 'newmarket-wards' AND boundaries_version = '2003'
       AND boundary_kind = 'district';
    IF auth <> 7 THEN
        RAISE EXCEPTION 'Expected 7 authoritative Newmarket wards, found % — '
          'run the load first', auth;
    END IF;
END $$;

DELETE FROM constituency_boundaries
 WHERE source_set = 'newmarket-wards'
   AND boundaries_version = 'current'
   AND boundary_kind = 'district';

DO $$
DECLARE live int; ward5 int; csd int; orphans int;
BEGIN
    SELECT count(*) INTO live FROM constituency_boundaries
     WHERE source_set = 'newmarket-wards' AND boundary_kind = 'district'
       AND effective_from <= CURRENT_DATE
       AND (effective_to IS NULL OR effective_to >= CURRENT_DATE);
    IF live <> 7 THEN
        RAISE EXCEPTION 'Newmarket has % live wards, expected 7', live;
    END IF;

    -- ★ The whole point of the migration.
    SELECT count(*) INTO ward5 FROM constituency_boundaries
     WHERE constituency_id = 'newmarket-wards/ward-5';
    IF ward5 <> 1 THEN
        RAISE EXCEPTION 'Ward 5 still absent';
    END IF;

    -- The mayoral polygon must survive.
    SELECT count(*) INTO csd FROM constituency_boundaries
     WHERE source_set = 'newmarket-wards' AND boundary_kind = 'municipality';
    IF csd <> 1 THEN
        RAISE EXCEPTION 'Newmarket municipality polygon lost';
    END IF;

    SELECT count(*) INTO orphans FROM politicians p
     WHERE p.is_active AND p.constituency_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM constituency_boundaries b
                        WHERE b.constituency_id = p.constituency_id);
    IF orphans <> 0 THEN
        RAISE EXCEPTION 'cutover orphaned % sitting members', orphans;
    END IF;

    RAISE NOTICE 'Newmarket: 7 wards live, Ward 5 recovered';
END $$;

COMMIT;

SELECT refresh_map_views();
