authors:
  adminatthebunker:
    name: adminatthebunker
    description: Project lead, Canadian Political Data
    url: https://github.com/adminatthebunker
    avatar: https://github.com/adminatthebunker.png
